export const CSVTOJSON = [
    {
      "id": 301,
      "task": "Webservice",
      "Proxy": "API",
      "name": "HiStreet",
      "task_desc": "India country location as a WM place in our database.",
      "details": "Should be able to specifically choose India location while creating campaigns. This place should cover entire India. Should be this and only this one place that is covered by this name.",
      "estimate": 3,
      "actuals": 3,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 3394,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "track the time spent on each doc by user and no. of attempted ",
      "details": "1.Should able to track the time spent on each doc by user_x000D_\n2.Number of time user has been seen the doc._x000D_\n2.List of not seen user",
      "estimate": 2,
      "actuals": 18,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Angular JS"
    },
    {
      "id": 3394,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "track the time spent on each doc by user and no. of attempted ",
      "details": "1.Should able to track the time spent on each doc by user_x000D_\n2.Number of time user has been seen the doc._x000D_\n2.List of not seen user",
      "estimate": 2,
      "actuals": 18,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Angular JS"
    },
    {
      "id": 3433,
      "task": "Mobile - App Release",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "IFB APK and add LeaderBoard into ifb(APK size has to reduced)",
      "details": "-> Reduce app size by removing library added for opening pdf and use default pdf viewer app.(Change in code)_x000D_\n-> In report section, hide dashboard with report section, show only leaderboard_x000D_\n -> Document matrix feature added to ifb._x000D_\n-> Splash and some ui",
      "estimate": 9,
      "actuals": 6,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Angular JS"
    },
    {
      "id": 3522,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "HiStreet",
      "task_desc": "Feedback Campaign Management Screen",
      "details": "1. A Screen where the target users and the feedback card are chosen for the feedback Campaign._x000D_\n2. Option to compose the feedback card using java library if the feedback card is not available._x000D_\n3. Publish/ start feedback camapign.",
      "estimate": 3,
      "actuals": 3,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 3528,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Treding Documents",
      "details": "Create Dashboard_x000D_\nList the Most Visited(Time spent) docs, like most time spent pdf,video,audio and  training._x000D_\n_x000D_\nDisplay in tab like(Tab1- all-docs, Tab2- Treding docs )",
      "estimate": 6,
      "actuals": 6,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 3528,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Treding Documents",
      "details": "Create Dashboard_x000D_\nList the Most Visited(Time spent) docs, like most time spent pdf,video,audio and  training._x000D_\n_x000D_\nDisplay in tab like(Tab1- all-docs, Tab2- Treding docs )",
      "estimate": 6,
      "actuals": 6,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 3528,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Treding Documents",
      "details": "Create Dashboard_x000D_\nList the Most Visited(Time spent) docs, like most time spent pdf,video,audio and  training._x000D_\n_x000D_\nDisplay in tab like(Tab1- all-docs, Tab2- Treding docs )",
      "estimate": 6,
      "actuals": 6,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 3532,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Tracking the Document Manager List(Android)",
      "details": "Tracking time spent on All the documents in document Manager(Mobile)  and add the r",
      "estimate": 3,
      "actuals": 3,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 3532,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Tracking the Document Manager List(Android)",
      "details": "Tracking time spent on All the documents in document Manager(Mobile)  and add the r",
      "estimate": 3,
      "actuals": 3,
      "resource": "May Flower",
      "Month": "Nov",
      "Technology": "Angular JS"
    },
    {
      "id": 3650,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Add replicate option for all infocapture form",
      "details": "Any form can be replicated._x000D_\n A replicated form's title will have the same old title but will have [copy] in the end_x000D_\nIn a replicated form all the section will be the same._x000D_\nA replicated form will have all the data across all the three forms same as the f",
      "estimate": 19,
      "actuals": 15,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "Python"
    },
    {
      "id": 3668,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "MH Grasim",
      "task_desc": "Add new form elements in the existing CDE Screen",
      "details": "Provision to input:_x000D_\n1)      Preferred language of Call_x000D_\n2)      Preferred Time of Call: Text box_x000D_\n3)      Preferred feedback mode: Choose from three options: SMS/EMAIL/DIRECT CALL",
      "estimate": 7,
      "actuals": 6,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 3759,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Trending Training",
      "details": "1. Trending top 7 trainings of the current month_x000D_\n2.Trending top 7 trainings of the Previous month_x000D_\n3. Trending top  7 Trainings of selected date(from-date to To-date)_x000D_\n4. create template(HTML Design) for the report and add to  admin Dashboard_x000D_\n_x000D_\nPlease f",
      "estimate": 12,
      "actuals": 12,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Angular JS"
    },
    {
      "id": 3760,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Top 7 Trending Docs",
      "details": "1. Trending top 7 docs(pdf,mp4,mp3) of the current month_x000D_\n2.Trending top 7 docs(pdf,mp4,mp3)of the Previous month_x000D_\n3. Trending top 7 docs(pdf,mp4,mp3)of selected date(from-date to To-date)_x000D_\n4. Filter by docs(pdf,mp4,mp3) _x000D_\n5. create template(HTML Design) ",
      "estimate": 9,
      "actuals": 9,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Angular JS"
    },
    {
      "id": 3760,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Top 7 Trending Docs",
      "details": "1. Trending top 7 docs(pdf,mp4,mp3) of the current month_x000D_\n2.Trending top 7 docs(pdf,mp4,mp3)of the Previous month_x000D_\n3. Trending top 7 docs(pdf,mp4,mp3)of selected date(from-date to To-date)_x000D_\n4. Filter by docs(pdf,mp4,mp3) _x000D_\n5. create template(HTML Design) ",
      "estimate": 9,
      "actuals": 9,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Angular JS"
    },
    {
      "id": 3812,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Training Taken Report",
      "details": "Training taken report(Training Completed) with autocomplete filter likes Training, Zone, State, Manager, RetailerType._x000D_\nDisplay the Training Not Taken Report(Training Not Completed) for the particular Training._x000D_\n_x000D_\nPlease find the attachement for the same",
      "estimate": 18,
      "actuals": 18,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 3853,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Enterprise",
      "task_desc": "Add new rule to calculate points in jnjccl",
      "details": "Add new rule to calculate points for jnjccl._x000D_\nReset points in database._x000D_\nUpdate point calculation from specific date._x000D_\nsetup local system for jnjccl.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "Python"
    },
    {
      "id": 3860,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Report Dashboard( Dynamically generate the table based on fields are selected )",
      "details": "- Dynamically generate the table based on fields are selected by the user(Like: user can select the fields to be display in to the table from the field list )_x000D_\n_x000D_\n-User can be select multiple values in the search filter (autocomplete with multiple values )",
      "estimate": 14,
      "actuals": 21,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 3860,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Report Dashboard( Dynamically generate the table based on fields are selected )",
      "details": "- Dynamically generate the table based on fields are selected by the user(Like: user can select the fields to be display in to the table from the field list )_x000D_\n_x000D_\n-User can be select multiple values in the search filter (autocomplete with multiple values )",
      "estimate": 14,
      "actuals": 21,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 3861,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Graph for training taken report",
      "details": "- Dynamically generate the graph based on the search filters (like Search can be by date)_x000D_\n_x000D_\n",
      "estimate": 9,
      "actuals": 18,
      "resource": "May Flower",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 3880,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "MH Madura",
      "task_desc": "BnM : My Action Required",
      "details": "Add UID Filter",
      "estimate": 5,
      "actuals": 5,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 3880,
      "task": "Web - Search",
      "Proxy": "Report",
      "name": "MH Madura",
      "task_desc": "BnM : My Action Required",
      "details": "Add UID Filter",
      "estimate": 5,
      "actuals": 5,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 3885,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "MH Madura",
      "task_desc": "SM : Prompts in screen",
      "details": "Prompts in all store manager tabs. See PPT slides 7 - 12",
      "estimate": 9,
      "actuals": 12,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 3958,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Infocapture : Add section break in infocapture form",
      "details": "One more field need to add in field wrapper and theme it._x000D_\nThen we can add section break in our form creation steps._x000D_\nTest and push on Qa server.",
      "estimate": 9,
      "actuals": 11,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "C#"
    },
    {
      "id": 4021,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Add Save as draft feature  in point system.",
      "details": "Step 3 point capture section in infocapture form need  to save as draft and again we can edit it ._x000D_\nAfter deploy infocapture form we can't edit points  again._x000D_\nTesting_x000D_\n",
      "estimate": 9,
      "actuals": 8,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "C#"
    },
    {
      "id": 4049,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Point System : Add points details in all reports.",
      "details": "Add Point capture infomation  in all report according to user and accounts - changes in  pdf , view report and excel report._x000D_\nEach report having point section with some calculation and total points.",
      "estimate": 25,
      "actuals": 25,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "C#"
    },
    {
      "id": 4049,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Silver",
      "task_desc": "Point System : Add points details in all reports.",
      "details": "Add Point capture infomation  in all report according to user and accounts - changes in  pdf , view report and excel report._x000D_\nEach report having point section with some calculation and total points.",
      "estimate": 25,
      "actuals": 25,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "Python"
    },
    {
      "id": 4081,
      "task": "Web - Edit",
      "Proxy": "API",
      "name": "Bsharp Enterprise",
      "task_desc": "Marketing profile for Trauma and joints",
      "details": "The ultimate aim to give a complete access like BU head._x000D_\n1. Cannot submit a submission_x000D_\n2. Cannot add doctor/hospital to the master pool_x000D_\n3. Can add user from the master pool to my doctors_x000D_\n4. Can view all dashboard.",
      "estimate": 15,
      "actuals": 15,
      "resource": "Anita Stein",
      "Month": "Oct",
      "Technology": "Python"
    },
    {
      "id": 4090,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Change in logic for capture surgery in trauma",
      "details": "Add fields in database to store more details for surgery capture._x000D_\nChange logic in surgery capture process._x000D_\nCreate one function to store all previous capture details like doctor info , salesperson details and hospital data in new table field._x000D_\nChange in ",
      "estimate": 12,
      "actuals": 12,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4189,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas :  Changes in save as draft feature for Infocapture form.",
      "details": "Changes in save as draft feature for Infocapture form._x000D_\nNeed to add multiple rules also in save as draft functionality.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4210,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Joints : Add Marketing & BU Role for new dashboard",
      "details": "Add two more roles Marketing &  BU and create new dashboard. _x000D_\nIf these two in all franchise then they can see both franchise's dashboard ._x000D_\n_x000D_\nBusiness Logic: _x000D_\n_x000D_\nMarketing: Various possibilities:_x000D_\na) One marketing guy can be part of one franchisee only_x000D_\n",
      "estimate": 12,
      "actuals": 12,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4240,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "MH Madura",
      "task_desc": "intimations add reminder",
      "details": "in the intimations tab, for open intimations add a date field called \"add reminder\" user should be able to select the date in the view and save it._x000D_\n_x000D_\nthe intimations section in the dashboard should show count of intimations that are open where reminder i",
      "estimate": 18,
      "actuals": 13,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 4240,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "MH Madura",
      "task_desc": "intimations add reminder",
      "details": "in the intimations tab, for open intimations add a date field called \"add reminder\" user should be able to select the date in the view and save it._x000D_\n_x000D_\nthe intimations section in the dashboard should show count of intimations that are open where reminder i",
      "estimate": 18,
      "actuals": 13,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 4245,
      "task": "Web - Edit",
      "Proxy": "API",
      "name": "Bsharp Enterprise",
      "task_desc": "Joints: Changes in procedure capture form",
      "details": "Changes in procedure capture form for joints.",
      "estimate": 3,
      "actuals": 3,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "C#"
    },
    {
      "id": 4284,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "MH Madura",
      "task_desc": "Happiness Wall ",
      "details": "1. show blog content in reverse chronological order in Happiness Wall_x000D_\n2. Alert users on huddle save that Delight story will be pushed to happiness wall",
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 4286,
      "task": "Web - Create Form",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Branding for client (upload Image and display it)",
      "details": "The client wants to personalization logo image according to their requirement ._x000D_\nUpload branding logo Image for all company in s3 bucket._x000D_\n_x000D_\n",
      "estimate": 12,
      "actuals": 8,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "C#"
    },
    {
      "id": 4295,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "MH Madura",
      "task_desc": "Dashboard changes and My  Intimations",
      "details": "Dashboard_x000D_\n1. add city in top 3 stores_x000D_\n2 .show â€œpendingâ€ intimations in messages_x000D_\nIntimation_x000D_\n1.flag by arm / rm / â€¦ for their stores_x000D_\n2 .check l2 filter in all relevant screens._x000D_\n",
      "estimate": 12,
      "actuals": 18,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 4295,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "MH Madura",
      "task_desc": "Dashboard changes and My  Intimations",
      "details": "Dashboard_x000D_\n1. add city in top 3 stores_x000D_\n2 .show â€œpendingâ€ intimations in messages_x000D_\nIntimation_x000D_\n1.flag by arm / rm / â€¦ for their stores_x000D_\n2 .check l2 filter in all relevant screens._x000D_\n",
      "estimate": 12,
      "actuals": 18,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4323,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas: Queue implementation ",
      "details": "Queue implementation for getting location name from lat,lng at the time of infocapture form submission._x000D_\nPush in Qa and testing.",
      "estimate": 7,
      "actuals": 7,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "C#"
    },
    {
      "id": 4330,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "MH Pantaloons",
      "task_desc": "Pantaloons App - Demo version",
      "details": "1.Screens_x000D_\n   1.1 Splash Screen_x000D_\n   1.2  Login screen_x000D_\n   1.3  Bar code scan Screen_x000D_\n   1.4 Offer detail screen_x000D_\n2. Integrating bar code scanner library_x000D_\n_x000D_\n3. Dummy Background logic_x000D_\n    _x000D_\n",
      "estimate": 27,
      "actuals": 22,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4330,
      "task": "Mobile - App Release",
      "Proxy": "API",
      "name": "MH Pantaloons",
      "task_desc": "Pantaloons App - Demo version",
      "details": "1.Screens_x000D_\n   1.1 Splash Screen_x000D_\n   1.2  Login screen_x000D_\n   1.3  Bar code scan Screen_x000D_\n   1.4 Offer detail screen_x000D_\n2. Integrating bar code scanner library_x000D_\n_x000D_\n3. Dummy Background logic_x000D_\n    _x000D_\n",
      "estimate": 27,
      "actuals": 22,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4367,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Changes in points form",
      "details": "Need to change way of storing points data in database for infocapture form.",
      "estimate": 3,
      "actuals": 4,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4388,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "MH Pantaloons",
      "task_desc": "Overlay on Bar code scanning screen and playing alert beep on scan",
      "details": null,
      "estimate": 9,
      "actuals": 14,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4418,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas Points : Remove point rules at the time of form creation.",
      "details": "Remove point rules at the time of form creation in point system._x000D_\npush on QA.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4437,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Changes in points logic & theming",
      "details": "Changes in Points logic_x000D_\n_x000D_\nb1) For image and sound question: Remove \"if not there assign X points\" clause _x000D_\n_x000D_\nb2) Numeric break in logic ( refer mail with subject : SaaS | Break in logic)_x000D_\n_x000D_\nb3) Date and time: We need \"on and before\" and \" on and after\" o",
      "estimate": 9,
      "actuals": 9,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4443,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Changes in point system report & Js validation for point capture form",
      "details": "Changes in point system report format in all places._x000D_\nNeed to put javascript validation for point capture popup form._x000D_\npush on Qa server.",
      "estimate": 10,
      "actuals": 11,
      "resource": "Anita Stein",
      "Month": "Nov",
      "Technology": "Python"
    },
    {
      "id": 4484,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Edit Webform Submission in backend ",
      "details": "Provide a link to edit web form Submission._x000D_\nChange photo & voice field in upload file._x000D_\ntheming webform edit form._x000D_\npush on server. ",
      "estimate": 18,
      "actuals": 18,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "Python"
    },
    {
      "id": 4497,
      "task": "Mobile - Screen",
      "Proxy": "Form",
      "name": "MH Pantaloons",
      "task_desc": "Pantaloons App - Screens",
      "details": "1. outbox_x000D_\n2. screen to show list of outward boxs created_x000D_\n3.  add weight screen_x000D_\n4. background logic and web service integration_x000D_\n5. Continuous  bar code scanning screen_x000D_\n6. Navigation Menu_x000D_\n",
      "estimate": 2,
      "actuals": 18,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4497,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "Pantaloons App - Screens",
      "details": "1. outbox_x000D_\n2. screen to show list of outward boxs created_x000D_\n3.  add weight screen_x000D_\n4. background logic and web service integration_x000D_\n5. Continuous  bar code scanning screen_x000D_\n6. Navigation Menu_x000D_\n",
      "estimate": 2,
      "actuals": 18,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 4498,
      "task": "Web - View",
      "Proxy": "Form",
      "name": "MH Pantaloons",
      "task_desc": "Portal Development : views and Background logic",
      "details": "1. learning VOB_x000D_\n2. creating stagging tables_x000D_\n3. article stock view_x000D_\n4. outward box views_x000D_\n5. Hu creation_x000D_\n6. Delivery creation_x000D_\n7. Pgi creation_x000D_\n8. reverse pgi creation_x000D_\n9. delete hu_x000D_\n10. delete delivery_x000D_\n11. cron job to reading data from stagging tables",
      "estimate": 3,
      "actuals": 27,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 4502,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas: Delete webform response ",
      "details": "Provide link to delete webform response with confirm popup box._x000D_\nTheming in confirm popup box._x000D_\nAdd status field in infogeon_infocapture_latlong table._x000D_\nChange the status of response._x000D_\npush in Qa and Production.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "Python"
    },
    {
      "id": 4510,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Adding total points for each infocapture form.",
      "details": "Adding total points for each infocapture form in point system._x000D_\nTotal Point Logic:_x000D_\nIf type is checkbox take sum of all options._x000D_\nif type is other than checkbox take maximum point.",
      "estimate": 7,
      "actuals": 7,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "Python"
    },
    {
      "id": 4532,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "Bsharp Silver",
      "task_desc": "Bsharp Saas : Points | Validation for operators|  | Numeric | Date | Time",
      "details": "  1) Points | Validation for operators|  | Numeric | Date | Time_x000D_\n  Scenario one: _x000D_\n<5_x000D_\n<6_x000D_\nHere 7 is answer greater than 5 and 6. System should understand and throw an error_x000D_\nScenario two: _x000D_\n<=5_x000D_\n<=6_x000D_\nHere 7 is answer greater than 5 and 6. System should ",
      "estimate": 15,
      "actuals": 15,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "C#"
    },
    {
      "id": 4725,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Add Search box in response list of infocapture form",
      "details": "Add Search box in response list of infocapture form._x000D_\ntheming ",
      "estimate": 5,
      "actuals": 5,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "C#"
    },
    {
      "id": 4746,
      "task": "Report",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Changes in all function for National Manager in joints.",
      "details": " NSM- For this, do you want them to have the ability to submit procedures? Also, if the NSM does make entries, and we do let it be visible in the YTD, MTD section only the NSM will be able to view the data. Do we still want to do this? â€“ remove surgery ad",
      "estimate": 9,
      "actuals": 9,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "C#"
    },
    {
      "id": 4792,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Building a summary dashboard for admin Role in Trauma",
      "details": "Create trauma & joints dashboard for admin role in joints._x000D_\nTheming for both dashboard._x000D_\npush on qa & production.",
      "estimate": 18,
      "actuals": 18,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "Python"
    },
    {
      "id": 4980,
      "task": "Web - Reports mail",
      "Proxy": "Report",
      "name": "Bsharp Enterprise",
      "task_desc": "Enterprise Sales Report  ",
      "details": "local setup for enterprise project._x000D_\nCreate function to generate sales report. _x000D_\nSend sales report mail to amgr for their team ._x000D_\nNeed To create queue to process email.",
      "estimate": 2,
      "actuals": 18,
      "resource": "Anita Stein",
      "Month": "Dec",
      "Technology": "Python"
    },
    {
      "id": 5006,
      "task": "Mobile - Screen",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "Auto beam scanner and Manual Barcode integration with APP,  Message changes",
      "details": null,
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 5007,
      "task": "Mobile - Screen",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "APP changes",
      "details": "1. Logout option_x000D_\n2. Display Username and Sap code in app_x000D_\n3. Activity label changes_x000D_\n4. App version  display_x000D_\n5. Article scan screen  design changes",
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 5013,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "MH Pantaloons",
      "task_desc": "Store contact upload,view edit",
      "details": null,
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 5013,
      "task": "Web - View",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "Store contact upload,view edit",
      "details": null,
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 5703,
      "task": "Mobile - Screen",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "pre selection of stores",
      "details": null,
      "estimate": 5,
      "actuals": 5,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 5926,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : Gate Pass generation",
      "details": "1) Gate Pass creation_x000D_\n Form to create the gate pass,print gate pass, upload SAP,_x000D_\n2)  View for Gate passes generated with reprint option.",
      "estimate": 15,
      "actuals": 20,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 5926,
      "task": "Web - View",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : Gate Pass generation",
      "details": "1) Gate Pass creation_x000D_\n Form to create the gate pass,print gate pass, upload SAP,_x000D_\n2)  View for Gate passes generated with reprint option.",
      "estimate": 15,
      "actuals": 20,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 5926,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : Gate Pass generation",
      "details": "1) Gate Pass creation_x000D_\n Form to create the gate pass,print gate pass, upload SAP,_x000D_\n2)  View for Gate passes generated with reprint option.",
      "estimate": 15,
      "actuals": 20,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 5927,
      "task": "Mobile - Screen",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "HHT APP : Item enquiry screen",
      "details": "refer wireframe and BRD shared",
      "estimate": 15,
      "actuals": 15,
      "resource": "John Smith",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 5928,
      "task": "Mobile - Screen",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "HHT APP : Variant Info screen ",
      "details": "refere wireframe and BRD / SRS",
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 5931,
      "task": "Webservice",
      "Proxy": "API",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : webservices for Offers and Article master",
      "details": null,
      "estimate": 6,
      "actuals": 6,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 5933,
      "task": "Web - Create Form",
      "Proxy": "Process",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : Deleting Article from Box",
      "details": "Delete any article from box  based on status of box",
      "estimate": 5,
      "actuals": 5,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 5933,
      "task": "Web - Edit",
      "Proxy": "Form",
      "name": "MH Pantaloons",
      "task_desc": "HHT Portal : Deleting Article from Box",
      "details": "Delete any article from box  based on status of box",
      "estimate": 5,
      "actuals": 5,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Java"
    },
    {
      "id": 6502,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing Huddle Dashboard Feedback Graphs",
      "details": null,
      "estimate": 5,
      "actuals": 5,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 6782,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "AB Yarn",
      "task_desc": "Transaction upload view",
      "details": null,
      "estimate": 2,
      "actuals": 3,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 6968,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "AB Yarn",
      "task_desc": "Testing: Action Item View/Action Closure/Mailers Changes",
      "details": "Action Item View changes: new columns added, filter bug fixes, duplicate records removal._x000D_\nMailers:  Daily Feedback mail, Action creation mail_x000D_\nAction Closure form: bug in 'attach file' option",
      "estimate": 7,
      "actuals": 7,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 7094,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Wealth Management",
      "task_desc": "Testing - CXO Dashboard of all Graphs",
      "details": null,
      "estimate": 32,
      "actuals": 18,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 7127,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "MH Pantaloons",
      "task_desc": "Testing Pujo Requirements/Site set Up",
      "details": "Pujo Site Set up_x000D_\nTesting against SRS attached.",
      "estimate": 20,
      "actuals": 12,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Java"
    },
    {
      "id": 7127,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "MH Pantaloons",
      "task_desc": "Testing Pujo Requirements/Site set Up",
      "details": "Pujo Site Set up_x000D_\nTesting against SRS attached.",
      "estimate": 20,
      "actuals": 12,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 7146,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing: Changes in CC Screen & Huddle Dahsboard",
      "details": "1. CRM Integration._x000D_\n_x000D_\n2. Up to 10 LX Drivers --> The limit of the number of Lx driver sets (Responses) should be increased from 2 to 10. Since it is a fixed number, there will be 1 row in the download sheet for each uid. No SRS done for this._x000D_\n_x000D_\n3. Plant",
      "estimate": 12,
      "actuals": 16,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 7146,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing: Changes in CC Screen & Huddle Dahsboard",
      "details": "1. CRM Integration._x000D_\n_x000D_\n2. Up to 10 LX Drivers --> The limit of the number of Lx driver sets (Responses) should be increased from 2 to 10. Since it is a fixed number, there will be 1 row in the download sheet for each uid. No SRS done for this._x000D_\n_x000D_\n3. Plant",
      "estimate": 12,
      "actuals": 16,
      "resource": "Jack Doe",
      "Month": "Oct",
      "Technology": "Javascript"
    },
    {
      "id": 7220,
      "task": "Web - View",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "GST changes for Invoice printing / download, show invoice number in views",
      "details": "1.  Receive invoice number from SAP via staging table_x000D_\n2.  Display invoice number in all required views_x000D_\n3.  print / download of invoice files uploaded to shared FTP path._x000D_\n4. UAT",
      "estimate": 13,
      "actuals": 15,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Java"
    },
    {
      "id": 7222,
      "task": "Web - View",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "RE-Requesting the HU Creation part in case the ARTICLE Qty rectified and gets deleted from PORTAL",
      "details": null,
      "estimate": 6,
      "actuals": 6,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Java"
    },
    {
      "id": 7224,
      "task": "Web - View",
      "Proxy": "Report",
      "name": "MH Pantaloons",
      "task_desc": "Deleting outward boxes",
      "details": null,
      "estimate": 9,
      "actuals": 9,
      "resource": "John Smith",
      "Month": "Dec",
      "Technology": "Java"
    },
    {
      "id": 7281,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "MH Grasim",
      "task_desc": "Testing Knowledge Management Search Page Requirement",
      "details": "Testing against document attached in task",
      "estimate": 18,
      "actuals": 3,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 7281,
      "task": "Web - Search",
      "Proxy": "Report",
      "name": "MH Grasim",
      "task_desc": "Testing Knowledge Management Search Page Requirement",
      "details": "Testing against document attached in task",
      "estimate": 18,
      "actuals": 3,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 7282,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "AB Yarn",
      "task_desc": "Testing Call Center people transaction view and details and filter",
      "details": null,
      "estimate": 5,
      "actuals": 3,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 7333,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing: Fixes in CC Screen/Action Closure Screen/PHP Fixes",
      "details": null,
      "estimate": 5,
      "actuals": 5,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Java"
    },
    {
      "id": 7427,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing changes/bug fixes in Customer Add/Edit & Other changes",
      "details": null,
      "estimate": 4,
      "actuals": 4,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 7427,
      "task": "Web - List",
      "Proxy": "Screen",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing changes/bug fixes in Customer Add/Edit & Other changes",
      "details": null,
      "estimate": 4,
      "actuals": 4,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 7442,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing Plant Huddle Dashboard Fixes",
      "details": null,
      "estimate": 6,
      "actuals": 6,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 7765,
      "task": "Web - Reports mail",
      "Proxy": "Report",
      "name": "AB Yarn",
      "task_desc": "Testing Changes in Action Closure Screen according to SRS  ",
      "details": null,
      "estimate": 9,
      "actuals": 7,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 7765,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "AB Yarn",
      "task_desc": "Testing Changes in Action Closure Screen according to SRS  ",
      "details": null,
      "estimate": 9,
      "actuals": 7,
      "resource": "Jack Doe",
      "Month": "Nov",
      "Technology": "Javascript"
    },
    {
      "id": 8088,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Acrylic",
      "task_desc": "Testing: Transaction Importer/View for Admin & Call center Login",
      "details": null,
      "estimate": 5,
      "actuals": 5,
      "resource": "Jack Doe",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 8145,
      "task": "Web - Reports mail",
      "Proxy": "Report",
      "name": "Acrylic",
      "task_desc": "Testing: Weekly Mailer",
      "details": "Weekly email(Feedback collected in previous week) to business admin and core team._x000D_\nNeed to create and save Feedbacks.",
      "estimate": 3,
      "actuals": 4,
      "resource": "Jack Doe",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 8254,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing Copper issues & change request in Manual Survey View & Dashboard",
      "details": "1. Checking User Dashboard Graph _x000D_\n2. Added request date in manual survey view for direct call mode._x000D_\n3. Checking due date extension 3 days issue.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Jack Doe",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 8254,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing Copper issues & change request in Manual Survey View & Dashboard",
      "details": "1. Checking User Dashboard Graph _x000D_\n2. Added request date in manual survey view for direct call mode._x000D_\n3. Checking due date extension 3 days issue.",
      "estimate": 5,
      "actuals": 5,
      "resource": "Jack Doe",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 8412,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Changes in quiz passed logic",
      "details": "Changes in passed/failed logic ._x000D_\nBased on points first or else based on no.of correct answer scored.",
      "estimate": 9,
      "actuals": 9,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8412,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "Changes in quiz passed logic",
      "details": "Changes in passed/failed logic ._x000D_\nBased on points first or else based on no.of correct answer scored.",
      "estimate": 9,
      "actuals": 9,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8413,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "Changes in modules passed percentages and certificates",
      "details": "Based on module settings and quiz passing %._x000D_\nOr based on the module completions._x000D_\n",
      "estimate": 8,
      "actuals": 8,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8413,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Changes in modules passed percentages and certificates",
      "details": "Based on module settings and quiz passing %._x000D_\nOr based on the module completions._x000D_\n",
      "estimate": 8,
      "actuals": 8,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8414,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Changes in html5/quiz seen status: new api",
      "details": "New api for getting information quiz/html5 seen or not after reinstall_x000D_\nApi integrations to app_x000D_\nChanges in local db._x000D_\nModifications in modules details page",
      "estimate": 22,
      "actuals": 22,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8414,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Changes in html5/quiz seen status: new api",
      "details": "New api for getting information quiz/html5 seen or not after reinstall_x000D_\nApi integrations to app_x000D_\nChanges in local db._x000D_\nModifications in modules details page",
      "estimate": 22,
      "actuals": 22,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8414,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "Changes in html5/quiz seen status: new api",
      "details": "New api for getting information quiz/html5 seen or not after reinstall_x000D_\nApi integrations to app_x000D_\nChanges in local db._x000D_\nModifications in modules details page",
      "estimate": 22,
      "actuals": 22,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8415,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "Quiz inside page changes and logic changes",
      "details": "Changes in quiz start, end ,summary and results pages._x000D_\nUi changes and color/icon chages_x000D_\nif u close app while taking quiz, take it as one attempt._x000D_\nQuestion/answer shuffle has to show in summary pages also_x000D_\nShuffle question without quiz messages ._x000D_\nEnd q",
      "estimate": 30,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8415,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Quiz inside page changes and logic changes",
      "details": "Changes in quiz start, end ,summary and results pages._x000D_\nUi changes and color/icon chages_x000D_\nif u close app while taking quiz, take it as one attempt._x000D_\nQuestion/answer shuffle has to show in summary pages also_x000D_\nShuffle question without quiz messages ._x000D_\nEnd q",
      "estimate": 30,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8415,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Quiz inside page changes and logic changes",
      "details": "Changes in quiz start, end ,summary and results pages._x000D_\nUi changes and color/icon chages_x000D_\nif u close app while taking quiz, take it as one attempt._x000D_\nQuestion/answer shuffle has to show in summary pages also_x000D_\nShuffle question without quiz messages ._x000D_\nEnd q",
      "estimate": 30,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8416,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "Quiz summary after max attempts",
      "details": "Quiz summary has to show after quiz max attempts exceeds._x000D_\nQuiz summary based on max points scored / max correct answers scored._x000D_\nIntermediate end quiz has to take one attempts._x000D_\nChanges in module completion based on quiz attempts.",
      "estimate": 20,
      "actuals": 20,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8416,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Quiz summary after max attempts",
      "details": "Quiz summary has to show after quiz max attempts exceeds._x000D_\nQuiz summary based on max points scored / max correct answers scored._x000D_\nIntermediate end quiz has to take one attempts._x000D_\nChanges in module completion based on quiz attempts.",
      "estimate": 20,
      "actuals": 20,
      "resource": "Amy Store",
      "Month": "Oct",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8417,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Changes in backend notification changes. App notifications",
      "details": "Each notification should show differently in notification bar._x000D_\nNotification inside page changes._x000D_\nBacked notification type and logic changes._x000D_\nClick event for notifications.",
      "estimate": 6,
      "actuals": 6,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8417,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "Changes in backend notification changes. App notifications",
      "details": "Each notification should show differently in notification bar._x000D_\nNotification inside page changes._x000D_\nBacked notification type and logic changes._x000D_\nClick event for notifications.",
      "estimate": 6,
      "actuals": 6,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8504,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Enterprise",
      "task_desc": "Backend View to reorder trainings under particular certificate",
      "details": "Create backend view for listing training under a certificate_x000D_\nReorder functionality for trainings_x000D_\nChanges in certification order after normal user login from pc_x000D_\nChanges in api to change the certificate training reorder._x000D_\n_x000D_\n_x000D_\n",
      "estimate": 7,
      "actuals": 7,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8504,
      "task": "Web - Create Form",
      "Proxy": "Form",
      "name": "Bsharp Enterprise",
      "task_desc": "Backend View to reorder trainings under particular certificate",
      "details": "Create backend view for listing training under a certificate_x000D_\nReorder functionality for trainings_x000D_\nChanges in certification order after normal user login from pc_x000D_\nChanges in api to change the certificate training reorder._x000D_\n_x000D_\n_x000D_\n",
      "estimate": 7,
      "actuals": 7,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8504,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Backend View to reorder trainings under particular certificate",
      "details": "Create backend view for listing training under a certificate_x000D_\nReorder functionality for trainings_x000D_\nChanges in certification order after normal user login from pc_x000D_\nChanges in api to change the certificate training reorder._x000D_\n_x000D_\n_x000D_\n",
      "estimate": 7,
      "actuals": 7,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Drupal PHP"
    },
    {
      "id": 8506,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "Ios Notification API: Backend changes",
      "details": "ios api for notification changes._x000D_\nBacked changes for notification updations._x000D_\nBackend db changes_x000D_\n",
      "estimate": 7,
      "actuals": 7,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8664,
      "task": "Web - Create Form",
      "Proxy": "Form",
      "name": "Bsharp Enterprise",
      "task_desc": "certificate with different template for each certificate",
      "details": "add filed for uploading certificate template image while adding course._x000D_\nChanges in tpl file_x000D_\nFixing alignments._x000D_\nChanges in certificate download code",
      "estimate": 15,
      "actuals": 15,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8664,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Enterprise",
      "task_desc": "certificate with different template for each certificate",
      "details": "add filed for uploading certificate template image while adding course._x000D_\nChanges in tpl file_x000D_\nFixing alignments._x000D_\nChanges in certificate download code",
      "estimate": 15,
      "actuals": 15,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8666,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase Demo: Backend changes, new api for token ids",
      "details": null,
      "estimate": 8,
      "actuals": 8,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8667,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Silver",
      "task_desc": "App s3 file upload changes, backend changes",
      "details": "S3 file upload changes on form submissions_x000D_\nChanges in image and voice file uploads_x000D_\nOffline form submission and s3 uploaded chnages_x000D_\nBackend api and report changes",
      "estimate": 25,
      "actuals": 25,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8667,
      "task": "Web - View",
      "Proxy": "Screen",
      "name": "Bsharp Silver",
      "task_desc": "App s3 file upload changes, backend changes",
      "details": "S3 file upload changes on form submissions_x000D_\nChanges in image and voice file uploads_x000D_\nOffline form submission and s3 uploaded chnages_x000D_\nBackend api and report changes",
      "estimate": 25,
      "actuals": 25,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8667,
      "task": "Webservice",
      "Proxy": "API",
      "name": "Bsharp Silver",
      "task_desc": "App s3 file upload changes, backend changes",
      "details": "S3 file upload changes on form submissions_x000D_\nChanges in image and voice file uploads_x000D_\nOffline form submission and s3 uploaded chnages_x000D_\nBackend api and report changes",
      "estimate": 25,
      "actuals": 25,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8847,
      "task": "Web - Dashboard Graph",
      "Proxy": "Report",
      "name": "Birla-Copper (Hindalco)",
      "task_desc": "Testing: 21.1 User Dashboard -Minor Modifications-03-Nov-2017",
      "details": "Testing against Document attached below.",
      "estimate": 4,
      "actuals": 4,
      "resource": "Jack Doe",
      "Month": "Dec",
      "Technology": "Javascript"
    },
    {
      "id": 8963,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Liza app: Serial barcode changes",
      "details": "Changes in serial barcode changes._x000D_\nChanges in validations_x000D_\nChanges in Full barcode concatenation",
      "estimate": 10,
      "actuals": 10,
      "resource": "Amy Store",
      "Month": "Nov",
      "Technology": "Core PHP"
    },
    {
      "id": 8963,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Liza app: Serial barcode changes",
      "details": "Changes in serial barcode changes._x000D_\nChanges in validations_x000D_\nChanges in Full barcode concatenation",
      "estimate": 10,
      "actuals": 10,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 8969,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase chat: Local db design and insert,updates,retrieve and delete funtions",
      "details": null,
      "estimate": 8,
      "actuals": 8,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 8970,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase MAuth integrations, and chatroom session creations",
      "details": "Mauthtication for user in firebase android_x000D_\nChatroom session creations_x000D_\nSession expire and create new session",
      "estimate": 20,
      "actuals": 20,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 8970,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase MAuth integrations, and chatroom session creations",
      "details": "Mauthtication for user in firebase android_x000D_\nChatroom session creations_x000D_\nSession expire and create new session",
      "estimate": 20,
      "actuals": 20,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 8971,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase chat: Ui changes - Module chat page",
      "details": null,
      "estimate": 25,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 9023,
      "task": "Mobile - Server Integration",
      "Proxy": "Process",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase sending message:Photo and text, api integrations",
      "details": "Sending api integrations for both photo and text type messages_x000D_\nPhoto options for gallery and camera pop ups_x000D_\nListeners for both photo and text type messages_x000D_\nDownloading others chat images, storing local data_x000D_\nDatabase integrations",
      "estimate": 30,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    },
    {
      "id": 9023,
      "task": "Mobile - Screen",
      "Proxy": "Screen",
      "name": "Bsharp Enterprise",
      "task_desc": "Firebase sending message:Photo and text, api integrations",
      "details": "Sending api integrations for both photo and text type messages_x000D_\nPhoto options for gallery and camera pop ups_x000D_\nListeners for both photo and text type messages_x000D_\nDownloading others chat images, storing local data_x000D_\nDatabase integrations",
      "estimate": 30,
      "actuals": 30,
      "resource": "Amy Store",
      "Month": "Dec",
      "Technology": "Core PHP"
    }
   ]